version: "3.3"

services:
  backend:
    container_name: backend
    restart: always
    build: ./backend
    environment:
      WORKER_CLASS: uvicorn_proxy_worker.UvicornProxyWorker
      FORWARDED_ALLOW_IPS: "*"
    depends_on:
      - nginx
      - redis

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    env_file:
     - ./services/mysql/.env
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data: